apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Giorno 1: commonLabels e namePrefix
namePrefix: dev-
commonLabels:
  env: development

# Giorno 1 & 5: Patching per repliche (Abbiamo rimosso il securityContext per risolvere il Permission Denied)
patches:
- target:
    kind: Deployment
    name: app-tigre
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
